
package org.exite.edi.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EdiServer", targetNamespace = "http://soap.edi.exite.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EdiServer {


    /**
     * 
     * @param fileName
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiFile
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDoc", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.GetDoc")
    @ResponseWrapper(localName = "getDocResponse", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.GetDocResponse")
    @Action(input = "http://soap.edi.exite.org/EdiServer/getDocRequest", output = "http://soap.edi.exite.org/EdiServer/getDocResponse")
    public EdiFile getDoc(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName);

    /**
     * 
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiFileList
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.GetListResponse")
    @Action(input = "http://soap.edi.exite.org/EdiServer/getListRequest", output = "http://soap.edi.exite.org/EdiServer/getListResponse")
    public EdiFileList getList(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user);

    /**
     * 
     * @param fileName
     * @param user
     * @param content
     * @return
     *     returns org.exite.edi.soap.EdiResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendDoc", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.SendDoc")
    @ResponseWrapper(localName = "sendDocResponse", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.SendDocResponse")
    @Action(input = "http://soap.edi.exite.org/EdiServer/sendDocRequest", output = "http://soap.edi.exite.org/EdiServer/sendDocResponse")
    public EdiResponse sendDoc(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "content", targetNamespace = "")
        byte[] content);

    /**
     * 
     * @param fileName
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "archiveDoc", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.ArchiveDoc")
    @ResponseWrapper(localName = "archiveDocResponse", targetNamespace = "http://soap.edi.exite.org/", className = "org.exite.edi.soap.ArchiveDocResponse")
    @Action(input = "http://soap.edi.exite.org/EdiServer/archiveDocRequest", output = "http://soap.edi.exite.org/EdiServer/archiveDocResponse")
    public EdiResponse archiveDoc(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName);

}
