
package org.exite.edi.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExiteWs", targetNamespace = "http://soap.edi.exite.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExiteWs {


    /**
     * 
     * @param fileName
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "archiveDoc", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.ArchiveDoc")
    @ResponseWrapper(localName = "archiveDocResponse", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.ArchiveDocResponse")
    public EdiResponse archiveDoc(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName);

    /**
     * 
     * @param fileName
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "archiveDocuments", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.ArchiveDocuments")
    @ResponseWrapper(localName = "archiveDocumentsResponse", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.ArchiveDocumentsResponse")
    public EdiResponse archiveDocuments(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        List<String> fileName);

    /**
     * 
     * @param fileName
     * @param user
     * @param content
     * @return
     *     returns org.exite.edi.soap.EdiResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendDoc", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.SendDoc")
    @ResponseWrapper(localName = "sendDocResponse", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.SendDocResponse")
    public EdiResponse sendDoc(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "content", targetNamespace = "")
        byte[] content);

    /**
     * 
     * @param fileName
     * @param remoteFolder
     * @param user
     * @param content
     * @return
     *     returns org.exite.edi.soap.EdiResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "uploadDoc", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.UploadDoc")
    @ResponseWrapper(localName = "uploadDocResponse", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.UploadDocResponse")
    public EdiResponse uploadDoc(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "content", targetNamespace = "")
        byte[] content,
        @WebParam(name = "remoteFolder", targetNamespace = "")
        String remoteFolder);

    /**
     * 
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiFileList
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.GetListResponse")
    public EdiFileList getList(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user);

    /**
     * 
     * @param fileName
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiFile
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDoc", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.GetDoc")
    @ResponseWrapper(localName = "getDocResponse", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.GetDocResponse")
    public EdiFile getDoc(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName);

    /**
     * 
     * @param fileName
     * @param user
     * @return
     *     returns org.exite.edi.soap.EdiFile
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDocuments", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.GetDocuments")
    @ResponseWrapper(localName = "getDocumentsResponse", targetNamespace = "http://soap.edi.exite.org", className = "org.exite.edi.soap.GetDocumentsResponse")
    public EdiFile getDocuments(
        @WebParam(name = "user", targetNamespace = "")
        EdiLogin user,
        @WebParam(name = "fileName", targetNamespace = "")
        List<String> fileName);

}
