
package org.exite.edi.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExiteWsService", targetNamespace = "http://soap.edi.exite.org", wsdlLocation = "http://localhost:8082/soap/exite.wsdl")
public class ExiteWsService
    extends Service
{

    private final static URL EXITEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXITEWSSERVICE_EXCEPTION;
    private final static QName EXITEWSSERVICE_QNAME = new QName("http://soap.edi.exite.org", "ExiteWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/soap/exite.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXITEWSSERVICE_WSDL_LOCATION = url;
        EXITEWSSERVICE_EXCEPTION = e;
    }

    public ExiteWsService() {
        super(__getWsdlLocation(), EXITEWSSERVICE_QNAME);
    }

    public ExiteWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXITEWSSERVICE_QNAME, features);
    }

    public ExiteWsService(URL wsdlLocation) {
        super(wsdlLocation, EXITEWSSERVICE_QNAME);
    }

    public ExiteWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXITEWSSERVICE_QNAME, features);
    }

    public ExiteWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExiteWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExiteWs
     */
    @WebEndpoint(name = "ExiteWsSoap11")
    public ExiteWs getExiteWsSoap11() {
        return super.getPort(new QName("http://soap.edi.exite.org", "ExiteWsSoap11"), ExiteWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExiteWs
     */
    @WebEndpoint(name = "ExiteWsSoap11")
    public ExiteWs getExiteWsSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.edi.exite.org", "ExiteWsSoap11"), ExiteWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXITEWSSERVICE_EXCEPTION!= null) {
            throw EXITEWSSERVICE_EXCEPTION;
        }
        return EXITEWSSERVICE_WSDL_LOCATION;
    }

}
